apiVersion: v1
kind: Service
metadata:
  name: plan-a-challenge
spec:
  selector:
    app: challenge-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-a-challenge
spec:
  selector:
    matchLabels:
      app: plan-a-challenge
  replicas: 4
  template:
    metadata:
      labels:
        app: plan-a-challenge
    spec:
      containers:
      - name: challenge-python
        image: challenge-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000